language: node_js
node_js:
  - 12.16.1

cache: npm

services:
  - xvfb

dist: trusty

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install: 
  - npm install

script:
  - xvfb-run npm test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master